### ISSUE TITLE
Feature Request: Support database and key prefix

### ISSUE THREAD

**Issue by suguru03** [keroxp/deno-redis#30]
I would like to define the database and key prefix, like ioredis.
https://github.com/luin/ioredis#connect-to-redis

**Comment by keroxp** [comment]
@suguru03 Desirable. If you are OK, I'll add you to collaborators, how about you?

**Comment by suguru03** [comment]
Thanks for the suggestion, I would love to be a collaborator!
I need the feature, so I can take a look at the issue 😄

**Comment by keroxp** [comment]
@suguru03 Added!

**Comment by suguru03** [comment]
Thanks! 😄
