### ISSUE TITLE
Compiler error when strict is false

### ISSUE THREAD

**Issue by suguru03** [keroxp/deno-redis#50]
I'm having a compiler issue when `strict` is false.
```ts
{
  "compilerOptions": {
    "strict": false
  }
}
```

![image](https://user-images.githubusercontent.com/8013633/75392522-13991580-58a1-11ea-8f15-de8293a28608.png)

https://github.com/keroxp/deno-redis/blob/58a197fbbc07aa0688afad59a872d5c719c41460/redis.ts#L528-L530

It would be nice if it checks the type properly, like `typeof reply !== "undefined"` instead of `reply != null`. 

I also tried only to enable `strictNullChecks`, but `std` complained. So I can't enable strict mode partially. 
```ts
{
  "compilerOptions": {
    "strict": false,
    "strictNullChecks": true
  }
}
```

**Comment by keroxp** [comment]
@suguru03 PR welcome
