### ISSUE TITLE
Allow to Subscribe to An Array of Strings

### ISSUE THREAD

**Issue by ebebbington** [keroxp/deno-redis#67]
Not sure if this could work (haven't seen how your code is architectured), but I'd like to be able to subscribe to many channels using one sub object. For example, I want to be able to do the following:

```typescript
const channels = ['channel.one', 'channel.two']
const sub = await redis.subscribe(channels);
```

I notice you can access the channel name when listening:

```typrscript
(async function() {
  for await (const { **channel**, message } of sub.receive()) {
    // on message
```

Which leads me to think maybe it's already possible? Other seems redundent?

**Comment by ebebbington** [comment]
I guess you can do:

```typescript
const sub = await redis.psubscribe('myappname.*')
// or
const sub = await redis.psubscribe('*')
```

But it'd be nice to specify a list instead of doing the above or creating a new object to listen on a different channel?

**Comment by ebebbington** [comment]
Also realised after some digging, it is possible but isn't clear in any of the documentation:

```typescript
const sub = await redis.subscribe('channel.one', 'test', 'channeltwo', ...)
```
I also notice in the declaration of the `subscribe` method that it's parameter is a `string[]`, but when I try to use this, it fails:

```
realtime_1  | error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'.
realtime_1  | 
realtime_1  | ► file:///var/www/realtime/app.ts:24:35
realtime_1  | 
realtime_1  | 24 const sub = await redis.subscribe(['test', 'realtime.comments.new']);

```
Is it possible for it to accept an array of strings?

**Comment by keroxp** [comment]
@ebebbington 

Try this:
```ts
const chans = ["a","b"];
redis.subscribe(...chans);
```

If you don't know ES Array spread syntax, see this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by ebebbington** [comment]
Oh that makes sense! I did see you using something like `subscribe(...something: string[])`, I’ll test it out then and I’m sure it’ll work, I’ll close this issue then

Thanks :) I’ll use your resource to look into the spread syntax more as I have never used or looked into it before
