### ISSUE TITLE
Query operation?

### ISSUE THREAD

**Issue by ddibiase** [keroxp/deno-redis#7]
I'm experimenting with RedisGraph right now and was wondering if deno-redis had support for running the `GRAPH.QUERY MotoGP "QUERY HERE"` syntax. Assuming just passing in the full query via a .exec method would suffice.

I'm *just* diving into this now so apologies if this is a bit basic.

**Comment by keroxp** [comment]
Not supported. Commands under https://redis.io/commands will be supported.
